'use client';
import {SiteHeader} from '../site-header';
import { useGame } from '../game-provider';

export default function Rules() {
  const {game}=useGame();
  const groups = Object.groupBy(game.categories.filter(category=>!category.retired&&category.id!=='voted-premerge'),(category) => category.group);
  return <main className="inner-page">
    <SiteHeader active="/rules" subtitle="League rulebook"/>
    <section className="inner-hero rules-hero"><p className="eyebrow"><span/> Official scoring</p><h1>Every move has a price.</h1><p>The same scoring system as the workbook, including the round-three blind-pick multiplier.</p></section>
    <section className="draft-rulebook"><h2>How the draft works</h2><ol>
      <li><strong>A fresh pool every round.</strong> Each castaway can be selected once within a round. All castaways return for the next round.</li>
      <li><strong>Rounds one and two.</strong> Round one uses reverse prior-season finish order; round two snakes back. Your two-castaway pair cannot match another player’s pair, even in reverse order.</li>
      <li><strong>Round three: shuffle and deal.</strong> Turn order is randomized separately. The full deck is shuffled and one face-down castaway is dealt to each player. The remaining castaways turn face up in the discard pile.</li>
      <li><strong>Keep or swap.</strong> Keep your unknown dealt card for a 1.25× multiplier on its points. Or take a face-up discard at 1×, forfeiting the bonus. Your original dealt card turns face up in the discard pile and can be taken by any later player.</li>
      <li><strong>Delayed reveals.</strong> A kept card reveals after two more blind cards are kept. Swaps do not advance the count. Any cards still hidden reveal when round three ends.</li>
      <li><strong>No earlier-round restrictions in round three.</strong> You may keep or swap for a castaway you already drafted in round one or two. Your choices are limited only by the current deal and discard pile.</li>
    </ol><p>Round-three decisions are final. The game master can submit a decision for an absent player under the same rules. Undo is available only before the blind deal opens.</p></section>
    <section className="rules-explanations"><article><h2>Before the merge</h2><p>Every active member of the winning tribe receives +2 for tribal immunity, including sit-outs. When a pre-merge Tribal Council is resolved, every remaining active member receives +1 survival and the castaway voted out receives −1. The first time each individual castaway attends Tribal Council, that castaway receives points equal to the episode number, including an eliminated castaway at that Council. Tribe swaps do not reset this castaway-specific history.</p></article><article><h2>Why a castaway leaves</h2><p>A castaway voted out before the merge receives −1. A voluntary quit receives −3 whether it happens before or after the merge. A medical evacuation and other removal are worth 0. Only one elimination outcome applies to a castaway; idol and advantage outcomes continue to score separately when relevant. A post-merge vote-out keeps the existing 0-point behavior.</p></article><article><h2>Rewards and stacking</h2><p>The primary tribal reward is +2 for every active member of the winning tribe and the secondary tribal reward is +1. An individual reward winner receives +2, selected participants receive +1, and the winner keeps +2 even when giving up the reward spot. Sitting out remains −1 and can stack with immunity or reward points.</p></article><article><h2>Merge bonuses</h2><p>Each pre-merge idol still held when the merge begins is worth +2 to its holder. If all 3 of your drafted castaways are still active when the merge begins, you receive +5.</p></article><article><h2>Post-merge votes and Final 5</h2><p>Only counted post-merge votes received count toward these totals. Votes nullified by an idol do not count. Extra votes and revotes count as additional votes.</p><p>At Final 5, the unique castaway with the most counted post-merge votes receives +10. The unique castaway with the fewest receives +5. No points are awarded for either rule when the high or low total is tied.</p></article><article><h2>Final 3</h2><p>The Final 5 castaway with the most counted post-merge votes receives an additional +5 if that castaway reaches Final 3. A tie at Final 5 creates no qualifying vote leader for this bonus.</p></article><article><h2>Episode controls</h2><p>“Still on the island” is +1 for every active castaway at the start of an episode. Majority-vote and blindside points are available only at or after the merge, and pre-merge survival and elimination points stop applying once the merge is reached.</p></article></section>
    <section className="rules-layout"><aside><div className="rule-summary"><span>${game.season.entryFee}</span><strong>Entry fee</strong><p>League entry for the new season.</p></div><div className="rule-summary"><span>3</span><strong>Castaways drafted</strong><p>Three rounds, with round three eligible for the blind-pick bonus.</p></div><div className="rule-summary"><span>1.25×</span><strong>Blind-pick bonus</strong><p>Keep the blind pick and that castaway’s score receives a 25% boost.</p></div></aside><div className="rules-groups">{Object.entries(groups).map(([group,items]) => <article key={group}><h2>{group}</h2><div>{items?.map((category) => <div className="scoring-rule" key={category.id}><span className={category.points < 0 ? 'negative' : ''}>{category.dynamicPoints==='episode'?'+Episode':`${category.points > 0 ? '+' : ''}${category.points}`}</span><p><strong>{category.label}</strong></p></div>)}</div></article>)}</div></section>
  </main>;
}
