'use client';
import {useEffect,useState,type FormEvent} from 'react';
import {calendarEpisodes,makeSchedule,type BroadcastSchedule} from '@/lib/discussions';
import {useGame} from '../game-provider';
import {discussionRequest,useDiscussions} from '../discussion-provider';

const weekdays=['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'];
function CalendarForm({saved,onSaved}:{saved:BroadcastSchedule|null;onSaved:()=>void}){
  const {game}=useGame(),{refresh}=useDiscussions();
  const [review,setReview]=useState<BroadcastSchedule|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
  function prepare(event:FormEvent<HTMLFormElement>){
    event.preventDefault();setError('');setMessage('');const data=new FormData(event.currentTarget);
    try{
      const overrides=String(data.get('overrides')??'').split('\n').filter(line=>line.trim()).map(line=>{const [episode,date]=line.trim().split(/\s+/);return {episode:Number(episode),date:date==='hold'?null:date};});
      const schedule=makeSchedule({season:game.season.number,weekday:Number(data.get('weekday')),startDate:data.get('startDate'),localTime:data.get('localTime'),timeZone:data.get('timeZone'),firstEpisode:Number(data.get('firstEpisode')),episodeCount:Number(data.get('episodeCount')),skippedDates:String(data.get('skippedDates')).split(/[\s,]+/).filter(Boolean),overrides},game.season.number,new Date().toISOString());
      calendarEpisodes(schedule);setReview(schedule);
    }catch(error){setError(error instanceof Error?error.message:'Check the broadcast calendar.');}
  }
  async function confirmCalendar(){
    if(busy||!review)return;setBusy(true);setError('');
    try{await discussionRequest({action:'save-schedule',...review,expectedUpdatedAt:saved?.updatedAt??''});await refresh();setReview(null);setMessage('Calendar saved. Discussions open automatically at these times.');onSaved();}catch(error){setError(error instanceof Error?error.message:'Could not save calendar.');}finally{setBusy(false);}
  }
  return <div><form className="community-form" onSubmit={prepare} onChange={()=>setReview(null)}><fieldset disabled={busy}><div className="broadcast-fields"><label>First episode number<input name="firstEpisode" type="number" min="1" max="9999" defaultValue={saved?.firstEpisode??1} required/></label><label>Number of episodes<input name="episodeCount" type="number" min="1" max="60" defaultValue={saved?.episodeCount??16} required/></label><label>Broadcast weekday<select name="weekday" defaultValue={saved?.weekday??3}>{weekdays.map((day,index)=><option value={index} key={day}>{day}</option>)}</select></label><label>First broadcast date<input name="startDate" type="date" defaultValue={saved?.startDate??''} required/></label><label>Local opening time<input name="localTime" type="time" defaultValue={saved?.localTime??''} required/></label><label>IANA time zone<input name="timeZone" defaultValue={saved?.timeZone??'America/New_York'} required maxLength={100}/></label></div><label>Skipped broadcast weeks<textarea name="skippedDates" rows={2} defaultValue={saved?.skippedDates.join('\n')??''} placeholder="One YYYY-MM-DD date per line. Later episode numbers shift by a week."/></label><label>Individual episode overrides<textarea name="overrides" rows={3} defaultValue={saved?.overrides.map(item=>`${item.episode} ${item.date??'hold'}`).join('\n')??''} placeholder={'4 2026-10-14\n5 hold'}/></label><p className="community-note">Enter confirmed dates only. An override uses “episode YYYY-MM-DD”; “episode hold” leaves that discussion closed until rescheduled. Already-open discussions and individual manual overrides keep their openings. Recaps, scores and current scoring episode are preserved.</p><button>Review calendar</button></fieldset></form>{review&&<div className="broadcast-review"><h3>Confirm discussion openings</h3><p>Times use {review.timeZone}. Clocks changing in autumn use the first occurrence of a repeated local time.</p><ol>{calendarEpisodes(review).map(item=><li key={item.id}>Episode {item.episode} · {item.broadcastDate||'Held'}{item.discussionOpensAt?` · ${review.localTime} (${item.discussionOpensAt})`:''}</li>)}</ol><button type="button" disabled={busy} onClick={()=>void confirmCalendar()}>{busy?'Saving…':'Confirm calendar'}</button></div>}{error&&<p role="alert">{error}</p>}{message&&<p role="status">{message}</p>}</div>;
}
function EpisodeOverride({schedule}:{schedule:BroadcastSchedule|null}){
  const {game}=useGame(),{catalog,mutate}=useDiscussions(),[episode,setEpisode]=useState(game.season.currentEpisode),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
  const existing=catalog?.episodes.find(item=>item.id===`${game.season.number}-${episode}`);
  async function submit(event:FormEvent<HTMLFormElement>){
    event.preventDefault();if(busy)return;const data=new FormData(event.currentTarget),mode=(event.nativeEvent as SubmitEvent).submitter?.getAttribute('value');setBusy(true);setMessage('');
    try{await mutate({action:'override',episodeId:`${game.season.number}-${episode}`,expectedVersion:existing?.version??'',mode,date:data.get('date'),localTime:data.get('localTime'),timeZone:data.get('timeZone')});setMessage('Discussion opening updated. Scoring is unchanged.');}catch(error){setMessage(error instanceof Error?error.message:'Could not update opening.');}finally{setBusy(false);}
  }
  return <section className="discussion-override"><h3>Change one discussion</h3><form className="community-form" onSubmit={submit}><fieldset disabled={busy}><label>Episode number<input type="number" min="1" max="9999" value={episode} onChange={event=>setEpisode(Number(event.target.value))} required/></label><p>{existing?.opensAt?`Current opening: ${new Date(existing.opensAt).toLocaleString()}`:'Opening not confirmed.'}</p><div className="broadcast-fields" key={episode}><label>Corrected broadcast date<input name="date" type="date" defaultValue={existing?.broadcastDate??''}/></label><label>Local opening time<input name="localTime" type="time" defaultValue={schedule?.localTime??''}/></label><label>IANA time zone<input name="timeZone" defaultValue={schedule?.timeZone??'America/New_York'}/></label></div><div className="community-actions"><button name="mode" value="schedule">Save new opening</button><button name="mode" value="open">Open immediately</button><button name="mode" value="hold">Hold discussion</button></div><p className="community-note">Holding an already-open discussion temporarily prevents reads and posts. Comments stay attached to the episode. To skip a broadcast week and shift later episodes, use the calendar’s skipped dates.</p></fieldset></form>{message&&<p role="status">{message}</p>}</section>;
}
export function DiscussionSchedule(){
  const {game,cloud}=useGame(),[reload,setReload]=useState(0),[state,setState]=useState<{schedule:BroadcastSchedule|null;loaded:boolean;error:string}>({schedule:null,loaded:false,error:''});
  useEffect(()=>{if(!cloud)return;const abort=new AbortController();discussionRequest<{schedule:BroadcastSchedule|null}>({view:'schedule',season:game.season.number},true,abort.signal).then(result=>setState({...result,loaded:true,error:''})).catch(error=>{if(!abort.signal.aborted)setState({schedule:null,loaded:true,error:error instanceof Error?error.message:'Could not load calendar.'});});return()=>abort.abort();},[cloud,game.season.number,reload]);
  return <article className="admin-panel discussion-calendar"><h2>Automatic episode discussions</h2><p>Confirm the broadcast calendar once. League members can discuss each aired episode while scoring waits for you.</p>{!cloud?<p>Connect Firebase to configure shared discussion openings.</p>:state.error?<p role="alert">{state.error} <button type="button" onClick={()=>setReload(value=>value+1)}>Retry calendar</button></p>:!state.loaded?<p role="status">Loading calendar…</p>:<><CalendarForm key={`${game.season.number}-${reload}`} saved={state.schedule} onSaved={()=>setReload(value=>value+1)}/><EpisodeOverride schedule={state.schedule}/></>}</article>;
}
