'use client';
import Link from 'next/link'; import {FormEvent,useState} from 'react'; import {categories} from '@/lib/game-data'; import {useGame} from '../game-provider';
const value=(form:HTMLFormElement,name:string)=>String(new FormData(form).get(name)??'');
export default function Admin(){const{game,standings,user,isAdmin,cloud,login,logout,addScore,addAdjustment,savePick,addPlayer,setPlayerEmail,startDraft,toggleDraft,undoDraftPick,resetSeason}=useGame();const[saved,setSaved]=useState('');
 async function score(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=e.currentTarget;await addScore({castawayId:value(f,'castawayId'),categoryId:value(f,'categoryId'),episode:Number(value(f,'episode')),note:value(f,'note')});setSaved('Scoring action saved.');f.reset()}
 async function pick(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=e.currentTarget;await savePick({playerId:value(f,'playerId'),castawayId:value(f,'castawayId'),round:Number(value(f,'round')),pickNumber:Number(value(f,'pickNumber')),blind:new FormData(f).get('blind')==='on'});setSaved('Draft pick saved.')}
 async function adjust(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=e.currentTarget;await addAdjustment(value(f,'playerId'),Number(value(f,'points')),value(f,'note'));setSaved('Player adjustment saved.');f.reset()}
 async function player(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=e.currentTarget;await addPlayer(value(f,'name'),value(f,'email'));setSaved('Player added.');f.reset()}
 async function email(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=e.currentTarget;await setPlayerEmail(value(f,'playerId'),value(f,'email'));setSaved('Player sign-in email saved.')}
 async function beginDraft(){try{await startDraft();setSaved('Live draft started.')}catch(error){setSaved(error instanceof Error?error.message:'Unable to start draft.')}}
 if(cloud&&!user)return <main className="admin-shell"><section className="admin-intro"><div><p className="eyebrow">Game master</p><h1>Sign in to run Survivor 51.</h1><p>Players can view the public leaderboard without signing in. Only the configured administrator can change the game.</p><button className="primary-button" onClick={login}>Sign in with Google</button></div></section></main>;
 if(!isAdmin)return <main className="admin-shell"><section className="admin-intro"><div><h1>This account is not the game master.</h1><p>You are signed in as <strong>{user?.email??'an unknown account'}</strong>. Sign out, then choose <strong>donohue.js@gmail.com</strong>.</p><button className="secondary-button" onClick={logout}>Sign out</button></div></section></main>;
 return <main className="admin-shell"><header className="admin-header"><Link className="brand" href="/"><span className="brand-mark">51</span><span><strong>Game Master</strong><small>Fantasy Survivor control room</small></span></Link><div><span>{user?.email??'Local setup mode'}</span>{user&&<button className="quiet-link" onClick={logout}>Sign out</button>}</div></header><section className="admin-intro"><div><p className="eyebrow">Protected controls</p><h1>Run the game without the spreadsheet scramble.</h1><p>Add a weekly action once. Castaway totals and every owner’s leaderboard score update automatically.</p></div><div className="admin-kpis"><span><strong>{standings.length}</strong>players</span><span><strong>{game.castaways.length}</strong>castaways</span><span><strong>{game.draftPicks.length}</strong>picks</span></div></section>{!cloud&&<p className="setup-notice">Local setup mode: connect Firebase before publishing so everyone sees the same data.</p>}{saved&&<p className="success-banner">{saved}</p>}
 <section className="admin-grid"><article className="admin-panel accent-panel"><div className="admin-panel-title"><span>01</span><div><p>Weekly scoring</p><h2>Add a castaway action</h2></div></div><form onSubmit={score} className="admin-form"><label>Episode<input name="episode" type="number" min="1" defaultValue={game.season.currentEpisode} required/></label><label>Castaway<select name="castawayId">{game.castaways.map((c)=><option key={c.id} value={c.id}>{c.shortName}</option>)}</select></label><label className="wide">Action / milestone<select name="categoryId">{categories.map((c)=><option key={c.id} value={c.id}>{c.points>0?'+':''}{c.points} · {c.label}</option>)}</select></label><label className="wide">Note <span>optional</span><input name="note"/></label><button className="primary-button wide">Add points & update standings</button></form></article>
 <article className="admin-panel"><div className="admin-panel-title"><span>02</span><div><p>Draft room</p><h2>Record or change a pick</h2></div></div><form onSubmit={pick} className="admin-form"><label>Player<select name="playerId">{game.players.map((p)=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Castaway<select name="castawayId">{game.castaways.map((c)=><option key={c.id} value={c.id}>{c.shortName}</option>)}</select></label><label>Round<select name="round"><option>1</option><option>2</option><option>3</option></select></label><label>Pick #<input name="pickNumber" type="number" min="1" defaultValue="1"/></label><label className="checkbox-row wide"><input name="blind" type="checkbox"/> Keep blind pick for the 25% bonus</label><button className="secondary-button wide">Save draft pick</button></form></article>
 <article className="admin-panel"><div className="admin-panel-title"><span>03</span><div><p>Bonus desk</p><h2>Adjust a player score</h2></div></div><form onSubmit={adjust} className="admin-form"><label>Player<select name="playerId">{game.players.map((p)=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Points<input name="points" type="number" step=".01" defaultValue="1"/></label><label className="wide">Reason<input name="note" required/></label><button className="secondary-button wide">Apply adjustment</button></form></article>
 <article className="admin-panel recent-panel"><div className="admin-panel-title"><span>04</span><div><p>Audit trail</p><h2>Latest scoring items</h2></div></div><div className="event-list">{game.scoreEvents.slice().reverse().slice(0,12).map((event)=><div key={event.id}><span><strong>{game.castaways.find((c)=>c.id===event.castawayId)?.shortName??game.players.find((p)=>p.id===event.playerId)?.name}</strong><small>{event.note||categories.find((c)=>c.id===event.categoryId)?.label}</small></span><b className={event.points<0?'negative':''}>{event.points>0?'+':''}{event.points}</b></div>)}{!game.scoreEvents.length&&<p className="admin-empty">No Season 51 scoring items yet.</p>}</div></article></section>
 <section className="setup-section"><div><p className="eyebrow dark">League setup</p><h2>Player access and live draft</h2><p>Assign the Google email each player will use. Only the person currently on the clock can submit a pick.</p></div><div className="setup-grid"><form onSubmit={email} className="mini-form"><h3>Assign player email</h3><select name="playerId">{[...game.players].sort((a,b)=>a.draftSlot-b.draftSlot).map((p)=><option key={p.id} value={p.id}>Slot {p.draftSlot} · {p.name}{p.email?' · connected':''}</option>)}</select><input name="email" type="email" placeholder="Google sign-in email" required/><button>Save player access</button></form><div className="mini-form"><h3>Draft controls</h3><p>{game.players.filter((p)=>p.email).length} of {game.players.length} player emails assigned · Status: {game.draft.status}</p>{game.draft.status==='setup'||game.draft.status==='complete'?<button type="button" onClick={beginDraft}>Start a clean live draft</button>:<><button type="button" onClick={toggleDraft}>{game.draft.status==='live'?'Pause draft':'Resume draft'}</button><button type="button" onClick={undoDraftPick}>Undo last pick</button></>}</div><form onSubmit={player} className="mini-form"><h3>Add a player</h3><input name="name" placeholder="Display name" required/><input name="email" type="email" placeholder="Google email"/><button>Add player</button></form><div className="mini-form"><h3>Reset Season 51</h3><p>Deletes every draft pick and scoring action while restoring the confirmed Season 51 cast.</p><button type="button" onClick={()=>{if(confirm('Reset all Season 51 picks and scores?'))resetSeason()}}>Reset clean season</button></div></div></section></main>}
