'use client';
import Link from 'next/link'; import {FormEvent,useState} from 'react'; import {useGame} from '../game-provider';
import {AuthControls} from '../auth-controls';
import {ScoringManager} from './scoring-manager';
import {PlayerSignups} from './player-signups';
import {SeasonManager} from './season-manager';
const value=(form:HTMLFormElement,name:string)=>String(new FormData(form).get(name)??'');
export default function Admin(){const{game,standings,user,isAdmin,cloud,authLoading,authBusy,logout,addAdjustment,savePick,addPlayer,startDraft,toggleDraft,undoDraftPick,resetSeason}=useGame();const[saved,setSaved]=useState('');
 async function pick(e:FormEvent<HTMLFormElement>){try{e.preventDefault();const f=e.currentTarget;await savePick({playerId:value(f,'playerId'),castawayId:value(f,'castawayId'),round:Number(value(f,'round')),pickNumber:Number(value(f,'pickNumber')),blind:new FormData(f).get('blind')==='on'});setSaved('Draft pick saved.')}catch(error){setSaved(error instanceof Error?error.message:'Unable to save.')}}
 async function adjust(e:FormEvent<HTMLFormElement>){try{e.preventDefault();const f=e.currentTarget;await addAdjustment(value(f,'playerId'),Number(value(f,'points')),value(f,'note'));setSaved('Player adjustment saved.');f.reset()}catch(error){setSaved(error instanceof Error?error.message:'Unable to save.')}}
 async function player(e:FormEvent<HTMLFormElement>){try{e.preventDefault();const f=e.currentTarget;await addPlayer(value(f,'name'),'');setSaved('Player added.');f.reset()}catch(error){setSaved(error instanceof Error?error.message:'Unable to save.')}}
 async function beginDraft(){try{await startDraft();setSaved('Live draft started.')}catch(error){setSaved(error instanceof Error?error.message:'Unable to start draft.')}}
 if((!cloud&&!isAdmin)||authLoading||(!user&&!isAdmin))return <main className="admin-shell"><section className="admin-intro"><div><p className="eyebrow">Game master</p><h1>Sign in to run Survivor {game.season.number}.</h1><AuthControls/></div></section></main>;
 if(!isAdmin)return <main className="admin-shell"><section className="admin-intro"><div><h1>This account is not the game master.</h1><p>Use the league owner account, donohue.js@gmail.com.</p><AuthControls/></div></section></main>;
 return <main className="admin-shell"><header className="admin-header"><Link className="brand" href="/"><span className="brand-mark">{game.season.number}</span><span><strong>Game Master</strong><small>Fantasy Survivor control room</small></span></Link><div><span>{user?.email??'Local setup mode'}</span>{user&&<button className="quiet-link" disabled={authBusy} onClick={logout}>Sign out</button>}</div></header><section className="admin-intro"><div><p className="eyebrow">Protected controls</p><h1>Run the game without the spreadsheet scramble.</h1><p>Add a weekly action once. Castaway totals and every owner’s leaderboard score update automatically.</p></div><div className="admin-kpis"><span><strong>{standings.length}</strong>players</span><span><strong>{game.castaways.length}</strong>castaways</span><span><strong>{game.draftPicks.length}</strong>picks</span></div></section>{!cloud&&<p className="setup-notice">Local setup mode: connect Firebase before publishing so everyone sees the same data.</p>}{saved&&<p className="success-banner">{saved}</p>}
 {game.season.finalized?<p className="setup-notice">Final results are locked. Scoring is read-only until you open the next season below.</p>:<ScoringManager key={game.season.number}/>}
 <PlayerSignups/>
 <SeasonManager/>
 <section className="admin-grid">
 <article className="admin-panel"><div className="admin-panel-title"><span>02</span><div><p>Draft room</p><h2>Record or change a pick</h2></div></div><form onSubmit={pick} className="admin-form"><label>Player<select name="playerId">{game.players.map((p)=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Castaway<select name="castawayId">{game.castaways.map((c)=><option key={c.id} value={c.id}>{c.shortName}</option>)}</select></label><label>Round<select name="round"><option>1</option><option>2</option><option>3</option></select></label><label>Pick #<input name="pickNumber" type="number" min="1" defaultValue="1"/></label><label className="checkbox-row wide"><input name="blind" type="checkbox"/> Keep blind pick for the 25% bonus</label><button disabled={game.season.finalized} className="secondary-button wide">Save draft pick</button></form></article>
 <article className="admin-panel"><div className="admin-panel-title"><span>03</span><div><p>Bonus desk</p><h2>Adjust a player score</h2></div></div><form onSubmit={adjust} className="admin-form"><label>Player<select name="playerId">{game.players.map((p)=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Points<input name="points" type="number" step=".01" defaultValue="1"/></label><label className="wide">Reason<input name="note" required/></label><button disabled={game.season.finalized} className="secondary-button wide">Apply adjustment</button></form></article>
 <article className="admin-panel recent-panel"><div className="admin-panel-title"><span>04</span><div><p>Audit trail</p><h2>Latest scoring items</h2></div></div><div className="event-list">{game.scoreEvents.slice().reverse().slice(0,12).map((event)=><div key={event.id}><span><strong>{event.recipientName??game.castaways.find((c)=>c.id===event.castawayId)?.shortName??game.players.find((p)=>p.id===event.playerId)?.name}</strong><small>{event.actionLabel||game.categories.find((c)=>c.id===event.categoryId)?.label||'Adjustment'}{event.tribeName?` · ${event.tribeName}`:''}{event.episode?` · Episode ${event.episode}`:''}{event.note?` · ${event.note}`:''}</small></span><b className={event.points<0?'negative':''}>{event.points>0?'+':''}{event.points}</b></div>)}{!game.scoreEvents.length&&<p className="admin-empty">No Season 51 scoring items yet.</p>}</div></article></section>
 <section className="setup-section"><div><p className="eyebrow dark">League setup</p><h2>Player access and live draft</h2><p>Returning accounts stay linked to their league profile. Assign new signups above before starting the draft.</p></div><div className="setup-grid"><div className="mini-form"><h3>Draft controls</h3><p>{game.players.filter((p)=>p.uid||p.email).length} of {game.players.length} accounts linked · Status: {game.draft.status}</p>{game.draft.status==='setup'?<button disabled={game.season.finalized} type="button" onClick={beginDraft}>Start live draft</button>:<><button disabled={game.season.finalized} type="button" onClick={()=>toggleDraft().catch(error=>setSaved(error.message))}>{game.draft.status==='live'?'Pause draft':'Resume draft'}</button><button disabled={game.season.finalized} type="button" onClick={()=>undoDraftPick().catch(error=>setSaved(error.message))}>Undo last pick</button></>}</div><form onSubmit={player} className="mini-form"><h3>Add a new league profile</h3><input name="name" placeholder="New player name" required/><button disabled={game.season.finalized}>Add player</button></form><div className="mini-form"><h3>Reset current season’s draft and scores</h3><p>Deletes current picks, scores, and entry bonuses. Preserves profiles, payment checkmarks, castaways, and archived results.</p><button disabled={game.season.finalized} type="button" onClick={()=>{if(confirm(`Reset Season ${game.season.number} picks and scores? Profiles and archived results will remain.`))resetSeason().catch(error=>setSaved(error.message))}}>Reset clean season</button></div></div></section></main>}
