'use client';
import {useState,type FormEvent} from 'react';
import {useGame,type PlayerSignup} from '../game-provider';
import type {Player} from '@/lib/game-data';
import {PlayerName} from '../player-name';
import {playerDisplayName} from '@/lib/player-honors';
export function PlayerSignups(){
  const {game,signups,assignSignup,setPlayerPaid,setPlayerEmail,setPlayerActive,signupError,signupLoading}=useGame();
  const [message,setMessage]=useState(''),[busy,setBusy]=useState('');
  async function assign(signup:PlayerSignup,playerId:string){
    const profile=game.players.find(p=>p.id===playerId);if(!profile)return;
    if(!confirm(`Link ${signup.name} (${signup.email}) permanently to ${profile.name}'s league profile and history? This season: slot ${profile.draftSlot}. Future slots are based on final results.`))return;
    setBusy(signup.uid);try{await assignSignup(signup,playerId);setMessage(`${signup.name} is now linked to a permanent league profile.`);}catch(error){setMessage(error instanceof Error?error.message:'Unable to assign player.');}finally{setBusy('');}
  }
  async function paid(player:Player,value:boolean){setBusy(player.id);try{await setPlayerPaid(player.id,value);setMessage(`${player.name}: ${value?'paid':'unpaid'} for Season ${game.season.number}.`);}catch(error){setMessage(error instanceof Error?error.message:'Payment status was not saved.');}finally{setBusy('');}}
  async function saveEmail(event:FormEvent<HTMLFormElement>,player:Player){
    event.preventDefault();const form=event.currentTarget,email=String(new FormData(form).get('email')??'');
    setBusy(player.id);try{await setPlayerEmail(player.id,email);setMessage(`${player.name}'s email is assigned. The game master can make their picks if they cannot sign in.`);}catch(error){setMessage(error instanceof Error?error.message:'Unable to assign the email.');}finally{setBusy('');}
  }
  async function participation(player:Player,active:boolean){
    const prompt=active?`Add ${player.name} back to the Season ${game.season.number} roster?`:`Remove ${player.name} from the Season ${game.season.number} roster? Their profile and historical performance will be kept.`;
    if(!confirm(prompt))return;
    setBusy(player.id);try{await setPlayerActive(player.id,active);setMessage(`${player.name} ${active?'added to':'removed from'} the Season ${game.season.number} roster. Historical results are unchanged.`);}catch(error){setMessage(error instanceof Error?error.message:'Unable to update the season roster.');}finally{setBusy('');}
  }
  const sorted=[...game.players].sort((a,b)=>a.draftSlot-b.draftSlot);
  const active=sorted.filter(player=>player.active!==false),inactive=sorted.filter(player=>player.active===false);
  return <section className="signup-admin"><div><p className="eyebrow dark">Player check-in</p><h2>Profiles, slots, and payments</h2><p>Players are registered automatically when they sign in with Google on any page. Link each account to the correct existing league profile once—this also links its historical results. Returning players keep that profile automatically. A profile is permanent; its draft slot changes each season.</p></div>
    {message&&<p role="status">{message}</p>}{signupError&&<p role="alert" className="scoring-error">{signupError}</p>}
    <div className="signup-list">{signupLoading&&<p role="status">Loading registrations…</p>}{signups.map(signup=>{const assigned=game.players.find(p=>p.uid===signup.uid||p.id===signup.assignedPlayerId);return <article key={signup.uid}><div><strong>{signup.name}</strong><small>{signup.email}</small></div>{assigned?<div><strong>{assigned.active===false?'Not playing this season':'Profile locked · Slot '+assigned.draftSlot}</strong><small><PlayerName id={assigned.id} name={assigned.name} history={game.history}/> · stays linked to this profile</small></div>:<label>Link league profile<select value="" disabled={Boolean(busy)||game.draft.status!=='setup'||game.season.finalized} onChange={e=>e.target.value&&assign(signup,e.target.value)}><option value="">Choose an active league profile…</option>{active.map(player=><option value={player.id} key={player.id} disabled={Boolean(player.uid||(player.email&&player.email.toLowerCase()!==signup.email.toLowerCase()))}>{playerDisplayName(player.id,player.name,game.history)} · Slot {player.draftSlot}</option>)}</select></label>}<span className={assigned?.paid?'paid-badge paid':'paid-badge'}>{assigned?.paid?'Paid':assigned?'Unpaid':'Awaiting assignment'}</span></article>;})}{!signupLoading&&!signupError&&!signups.length&&<p>No players have signed up yet. Share the Draft board link.</p>}</div>
    <h3>Draft access for players without accounts</h3><p>Assign each unlinked player their unique email before starting the draft. They do not need to sign in for you to draft on their behalf. Email assignments are locked once the draft starts.</p>
    <div className="signup-list draft-email-list">{active.map(player=><article key={player.id}><div><strong>Slot {player.draftSlot} · <PlayerName id={player.id} name={player.name} history={game.history}/></strong><small>{player.uid?'Google account already linked':player.email||'No email assigned yet'}</small></div>{player.uid?<span className="paid-badge paid">Account linked</span>:<form className="draft-email-form" onSubmit={event=>void saveEmail(event,player)}><label>Email address<input type="email" name="email" required maxLength={254} defaultValue={player.email} disabled={Boolean(busy)||game.draft.status!=='setup'||game.season.finalized} placeholder="player@example.com"/></label><button disabled={Boolean(busy)||game.draft.status!=='setup'||game.season.finalized}>{busy===player.id?'Saving…':player.email?'Save email':'Assign email'}</button></form>}<button className="roster-toggle" type="button" disabled={Boolean(busy)||game.draft.status!=='setup'||game.season.finalized} onClick={()=>void participation(player,false)}>Remove from season</button></article>)}</div>
    {inactive.length>0&&<><h3>Not playing this season</h3><p>These profiles and past results are retained. Add one back to the current season if plans change.</p><div className="signup-list inactive-roster-list">{inactive.map(player=><article key={player.id}><div><strong><PlayerName id={player.id} name={player.name} history={game.history}/></strong><small>{player.email|| (player.uid?'Google account linked':'Profile retained')}</small></div><button className="roster-toggle" type="button" disabled={Boolean(busy)||game.draft.status!=='setup'||game.season.finalized} onClick={()=>void participation(player,true)}>Add back to season</button></article>)}</div></>}
    <h3>Season {game.season.number} payments · ${game.season.entryFee} per player</h3><p>{active.filter(p=>p.paid).length} of {active.length} active players marked paid. This is a manual receipt tracker, not an online payment service. It does not award bonus points or block draft access.</p>
    <div className="payment-list">{active.map(player=><label key={player.id}><input type="checkbox" aria-label={`Paid: ${player.name}`} disabled={Boolean(busy)} checked={Boolean(player.paid)} onChange={e=>paid(player,e.target.checked)}/><span><strong>Slot {player.draftSlot} · <PlayerName id={player.id} name={player.name} history={game.history}/></strong><small>{signups.find(s=>s.uid===player.uid)?.email||player.email||(player.uid?'Linked Google account':'Awaiting account assignment')}</small></span><b>{player.paid?'Paid':'Unpaid'}</b></label>)}</div>
  </section>;
}
