'use client';

import {useState,type FormEvent} from 'react';
import {eliminationReasonLabels,eliminationReasons,type Castaway,type EliminationReason,type Possession} from '@/lib/game-data';
import {activePossessions,episodeTribalCouncils,mergeIsActive,previewTribalCouncil,resolveRecipients,tribalCouncilId} from '@/lib/scoring';
import {useGame} from '../game-provider';
import {RecipientSelector,type RecipientSelection} from './recipient-selector';

const messageOf=(error:unknown)=>error instanceof Error?error.message:'Unable to save. Please try again.';

export function TribalCouncilManager({game,loading,onResolve,onAdd}:{game:ReturnType<typeof useGame>['game'];loading:boolean;onResolve:(input:Parameters<ReturnType<typeof useGame>['resolveTribalCouncil']>[0])=>Promise<void>;onAdd:(episode:number,number?:number)=>Promise<void>}){
  type PlayDraft={possessionId:string;playedByCastawayId:string;playedForCastawayId:string;successful?:boolean};
  type ShotDraft={id:string;castawayId:string;result:''|'safe'|'unsafe'};
  type VoteDraft={id:string;castawayId:string;countedVotes:string;nullifiedVotes:string;extraVotes:string;round:string};
  const councils=episodeTribalCouncils(game),first=councils[0];
  const [councilKey,setCouncilKey]=useState(first?.id??'');
  const [selection,setSelection]=useState<RecipientSelection>({mode:first?.attendeeMode??'tribe',tribeId:first?.tribeId,castawayIds:first?.attendeeIds??[]});
  const [eliminatedId,setEliminatedId]=useState(first?.eliminatedCastawayId??'');
  const [eliminationReason,setEliminationReason]=useState<EliminationReason>(first?.eliminationReason??'voted-out');
  const [plays,setPlays]=useState<PlayDraft[]>([]),[shots,setShots]=useState<ShotDraft[]>([]),[votes,setVotes]=useState<VoteDraft[]>([]);
  const [busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');
  const council=councils.find(item=>item.id===councilKey)??first;
  const merged=mergeIsActive(game),modes=merged?['all-active','custom','tribe'] as const:['tribe','custom'] as const;
  const attendeeChoices=game.castaways.filter(castaway=>castaway.status==='active');
  const attendeeCategory={id:'tribal-attendees',label:'Tribal attendees',points:0,group:'Tribal council',target:'tribe' as const,recipientModes:[...modes]};
  let attendees:Castaway[]=[];
  try{attendees=resolveRecipients(game,attendeeCategory,selection.mode,selection.tribeId,selection.castawayIds);}catch{attendees=[];}
  const attendingIds=new Set(attendees.map(castaway=>castaway.id));
  const items=activePossessions(game).filter(possession=>attendingIds.has(possession.castawayId));
  const resolved=Boolean(council?.status==='resolved');
  const completePlays=plays.every(play=>play.successful!==undefined),completeShots=shots.every(shot=>shot.castawayId&&shot.result);
  const itemPlays=plays.map(play=>({possessionId:play.possessionId,playedByCastawayId:play.playedByCastawayId,playedForCastawayId:play.playedForCastawayId||undefined,successful:Boolean(play.successful)}));
  const shotInputs=shots.filter(shot=>shot.castawayId&&shot.result).map(shot=>({castawayId:shot.castawayId,result:shot.result as 'safe'|'unsafe'}));
  const postMergeVotes=votes.filter(vote=>vote.castawayId).map(vote=>({castawayId:vote.castawayId,countedVotes:Number(vote.countedVotes||0),nullifiedVotes:Number(vote.nullifiedVotes||0),extraVotes:Number(vote.extraVotes||0),revote:Number(vote.round||1)>1,round:Number(vote.round||1)}));
  let preview:ReturnType<typeof previewTribalCouncil>|undefined,previewError='';
  if(council&&!resolved&&attendees.length){
    if(!completePlays)previewError='Choose Successful or Unsuccessful for every selected item.';
    else if(!completeShots)previewError='Choose an attending castaway and result for every Shot in the Dark row.';
    else if(merged&&!postMergeVotes.length)previewError='Add the counted votes for this post-merge Tribal Council before resolving it.';
    else try{preview=previewTribalCouncil(game,{tribalCouncilId:council.id,councilNumber:council.number,tribeId:selection.tribeId,attendeeMode:selection.mode,attendeeIds:attendees.map(castaway=>castaway.id),eliminatedCastawayId:eliminatedId||undefined,eliminationReason:eliminatedId?eliminationReason:undefined,episode:game.season.currentEpisode,note:'',expectedAttendeeIds:attendees.map(castaway=>castaway.id),itemPlays,shotsInTheDark:shotInputs,postMergeVotes});}catch(error){previewError=messageOf(error);}
  }
  function chooseCouncil(nextId:string){const next=councils.find(item=>item.id===nextId)??first;if(!next)return;setCouncilKey(next.id);setSelection({mode:next.attendeeMode,tribeId:next.tribeId,castawayIds:next.attendeeIds});setEliminatedId(next.eliminatedCastawayId??'');setEliminationReason(next.eliminationReason??'voted-out');setPlays([]);setShots([]);setVotes([]);setError('');}
  function toggleItem(possession:Possession,checked:boolean){setPlays(current=>checked?[...current,{possessionId:possession.id,playedByCastawayId:possession.castawayId,playedForCastawayId:possession.castawayId}]:current.filter(play=>play.possessionId!==possession.id));}
  function updatePlay(possessionId:string,change:Partial<PlayDraft>){setPlays(current=>current.map(play=>play.possessionId===possessionId?{...play,...change}:play));}
  function updateVote(id:string,change:Partial<VoteDraft>){setVotes(current=>current.map(vote=>vote.id===id?{...vote,...change}:vote));}
  async function addAnother(){setBusy(true);try{const number=Math.max(...councils.map(item=>item.number))+1;await onAdd(game.season.currentEpisode,number);setCouncilKey(tribalCouncilId(game,game.season.currentEpisode,number));setSelection({mode:merged?'all-active':'tribe',castawayIds:merged?attendeeChoices.map(castaway=>castaway.id):[]});setEliminatedId('');setEliminationReason('voted-out');setVotes([]);setMessage(`Tribal Council #${number} added.`);}catch(error){setError(messageOf(error));}finally{setBusy(false);}}
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();if(busy||!preview||!council)return;const data=new FormData(event.currentTarget);setBusy(true);setError('');setMessage('');try{await onResolve({tribalCouncilId:council.id,councilNumber:council.number,tribeId:selection.tribeId,attendeeMode:selection.mode,attendeeIds:attendees.map(castaway=>castaway.id),eliminatedCastawayId:eliminatedId||undefined,eliminationReason:eliminatedId?eliminationReason:undefined,episode:game.season.currentEpisode,note:String(data.get('note')??''),expectedAttendeeIds:attendees.map(castaway=>castaway.id),expectedFirstTimeAttendeeIds:preview.firstTimeAttendees.map(castaway=>castaway.id),expectedPreMerge:preview.preMerge,expectedTribeName:preview.tribe?.name,itemPlays,shotsInTheDark:shotInputs,postMergeVotes});setMessage(`Tribal Council #${council.number} resolved.`);setEliminatedId('');setEliminationReason('voted-out');setPlays([]);setShots([]);setVotes([]);}catch(error){setError(messageOf(error));}finally{setBusy(false);}}
  const newVote=()=>setVotes(current=>[...current,{id:crypto.randomUUID(),castawayId:'',countedVotes:'0',nullifiedVotes:'0',extraVotes:'0',round:'1'}]);
  return <article className="admin-panel accent-panel tribal-resolution">
    <div className="admin-panel-title"><span>TC</span><div><p>Repeatable episode event</p><h2>Tribal Councils</h2></div></div>
    <p>Choose the explicit attendees for each council. A castaway may attend more than one council in this episode; only elimination status removes them from later active selections.</p>
    <div className="tribal-council-list">{councils.map(item=><button type="button" key={item.id} className={`tribal-council-tab${item.id===council?.id?' selected':''}`} onClick={()=>chooseCouncil(item.id)}><span>{item.status==='resolved'?'✓':'○'}</span><strong>Tribal Council #{item.number}</strong><small>{item.status==='resolved'?'Resolved':'Awaiting resolution'}</small></button>)}</div>
    <button type="button" className="secondary-button" onClick={addAnother} disabled={loading||busy}>+ Add another Tribal Council</button>
    {council&&<form className="admin-form" onSubmit={submit}>
      <h3 className="wide">Tribal Council #{council.number}</h3>
      <RecipientSelector label="Tribal attendees" modes={[...modes]} castaways={attendeeChoices} tribes={game.tribes} value={selection} onChange={next=>{setSelection(next);setEliminatedId('');setEliminationReason('voted-out');setPlays([]);setShots([]);setVotes([]);}} disabled={busy||loading||resolved}/>
      <label className="wide">Castaway eliminated (optional)<select value={eliminatedId} onChange={event=>{setEliminatedId(event.target.value);setEliminationReason('voted-out');}} disabled={resolved||busy}><option value="">No elimination / not recorded</option>{attendees.map(castaway=><option key={castaway.id} value={castaway.id}>{castaway.name}</option>)}</select></label>
      {eliminatedId&&<label className="wide">Elimination reason<select value={eliminationReason} onChange={event=>setEliminationReason(event.target.value as EliminationReason)} disabled={resolved||busy}>{eliminationReasons.map(item=><option key={item} value={item}>{eliminationReasonLabels[item]}</option>)}</select></label>}
      {attendees.length>0&&<section className="tribal-optional-section"><h3>Idols &amp; Advantages Used Tonight</h3>{items.length?items.map(possession=>{const play=plays.find(item=>item.possessionId===possession.id);return <div className="tribal-item-row" key={possession.id}><label className="tribal-item-toggle"><input type="checkbox" checked={Boolean(play)} onChange={event=>toggleItem(possession,event.target.checked)} disabled={resolved}/><span><strong>{game.castaways.find(castaway=>castaway.id===possession.castawayId)?.name}</strong><small>{possession.itemName} · {possession.category==='idol'?'Idol':'Advantage'}</small></span></label>{play&&<div className="tribal-item-fields"><label>Played by<select value={play.playedByCastawayId} onChange={event=>updatePlay(possession.id,{playedByCastawayId:event.target.value})}>{attendees.map(castaway=><option key={castaway.id} value={castaway.id}>{castaway.name}</option>)}</select></label><label>Played for<select value={play.playedForCastawayId} onChange={event=>updatePlay(possession.id,{playedForCastawayId:event.target.value})}><option value="">No specific castaway</option>{attendees.map(castaway=><option key={castaway.id} value={castaway.id}>{castaway.name}</option>)}</select></label><fieldset className="tribal-success-choice"><legend>Successful?</legend><label><input type="radio" name={`success-${possession.id}`} checked={play.successful===true} onChange={()=>updatePlay(possession.id,{successful:true})}/> Yes</label><label><input type="radio" name={`success-${possession.id}`} checked={play.successful===false} onChange={()=>updatePlay(possession.id,{successful:false})}/> No</label></fieldset></div>}</div>; }):<p className="admin-feedback">No active idols or advantages held by attending castaways.</p>}</section>}
      {attendees.length>0&&<section className="tribal-optional-section"><div className="tribal-section-heading"><h3>Shot in the Dark</h3><button type="button" className="secondary-button" onClick={()=>setShots(current=>[...current,{id:crypto.randomUUID(),castawayId:'',result:''}])} disabled={busy||resolved}>+ Record Shot in the Dark</button></div>{shots.map((shot,index)=><div className="shot-row" key={shot.id}><label>Castaway<select value={shot.castawayId} onChange={event=>setShots(current=>current.map(item=>item.id===shot.id?{...item,castawayId:event.target.value}:item))} required><option value="">Choose a castaway…</option>{attendees.filter(castaway=>!shots.some((other,otherIndex)=>otherIndex!==index&&other.castawayId===castaway.id)).map(castaway=><option key={castaway.id} value={castaway.id}>{castaway.name}</option>)}</select></label><fieldset><legend>Result</legend><label><input type="radio" name={`shot-${shot.id}`} checked={shot.result==='safe'} onChange={()=>setShots(current=>current.map(item=>item.id===shot.id?{...item,result:'safe'}:item))}/> Safe</label><label><input type="radio" name={`shot-${shot.id}`} checked={shot.result==='unsafe'} onChange={()=>setShots(current=>current.map(item=>item.id===shot.id?{...item,result:'unsafe'}:item))}/> Unsafe</label></fieldset><button type="button" className="text-button" onClick={()=>setShots(current=>current.filter(item=>item.id!==shot.id))}>Remove</button></div>)}</section>}
      {merged&&attendees.length>0&&<section className="tribal-optional-section"><div className="tribal-section-heading"><div><h3>Counted votes received</h3><p className="admin-feedback">Count only votes that counted toward the result. Record idol-nullified votes separately; extra votes are included in counted votes, and revotes are additional rows.</p></div><button type="button" className="secondary-button" onClick={newVote} disabled={busy||resolved}>+ Add vote tally</button></div>{votes.map(vote=><div className="shot-row" key={vote.id}><label>Recipient<select value={vote.castawayId} onChange={event=>updateVote(vote.id,{castawayId:event.target.value})} disabled={busy||resolved}><option value="">Choose a castaway…</option>{attendees.map(castaway=><option key={castaway.id} value={castaway.id}>{castaway.name}</option>)}</select></label><label>Counted<input type="number" min="0" step="1" value={vote.countedVotes} onChange={event=>updateVote(vote.id,{countedVotes:event.target.value})} disabled={busy||resolved}/></label><label>Idol-nullified<input type="number" min="0" step="1" value={vote.nullifiedVotes} onChange={event=>updateVote(vote.id,{nullifiedVotes:event.target.value})} disabled={busy||resolved}/></label><label>Extra votes<input type="number" min="0" step="1" value={vote.extraVotes} onChange={event=>updateVote(vote.id,{extraVotes:event.target.value})} disabled={busy||resolved}/></label><label>Round<select value={vote.round} onChange={event=>updateVote(vote.id,{round:event.target.value})} disabled={busy||resolved}><option value="1">Initial vote</option><option value="2">Revote</option><option value="3">Revote 2</option></select></label><button type="button" className="text-button" onClick={()=>setVotes(current=>current.filter(item=>item.id!==vote.id))} disabled={busy||resolved}>Remove</button></div>)}</section>}
      {preview&&<div className="score-preview tribal-summary wide"><strong>TRIBAL COUNCIL SUMMARY · {preview.tribe?.name??'Custom attendees'} · Episode {preview.episode}</strong>{preview.postMergeVotes.length>0&&<><h3>Counted post-merge votes</h3><p>{preview.postMergeVotes.map(vote=>`${game.castaways.find(castaway=>castaway.id===vote.castawayId)?.name??'Unknown'} · ${vote.countedVotes} counted${vote.nullifiedVotes?` · ${vote.nullifiedVotes} nullified`:''}${vote.revote?' · revote':''}`).join(' · ')}</p></>}{preview.playedItems.length>0&&<><h3>Items used tonight</h3>{preview.playedItems.map(item=><p key={item.possession.id}>{item.playedBy.name} {item.input.successful?'successfully used':'played unsuccessfully'} {item.possession.itemName}{item.playedFor?` for ${item.playedFor.name}`:''}{item.input.successful?` → ${item.playedBy.name} +${item.possession.category==='idol'?5:2}`:''}</p>)}</>}{preview.shots.length>0&&<><h3>Shot in the Dark</h3>{preview.shots.map(shot=><p key={shot.castaway.id}>{shot.castaway.name} · {shot.input.result==='safe'?'Safe → +5':'Unsafe → -1'}</p>)}</>}{preview.eliminated&&<><h3>{preview.eliminated.name} eliminated</h3><p><strong>{eliminationReasonLabels[preview.eliminationReason]} · {preview.eliminationScoringActive?(preview.eliminationPenalty>0?'+':'')+preview.eliminationPenalty:'No new penalty in this episode'}</strong></p>{preview.pocketPossessions.length? <>{preview.pocketPossessions.map(possession=><p key={possession.id}>{possession.itemName} → {possession.category==='idol'?-10:-4}</p>)}<p><strong>Total automated possession penalty: {preview.pocketPossessions.reduce((total,possession)=>total+(possession.category==='idol'?-10:-4),0)}</strong></p></>:<p>No active idols or advantages remain in {preview.eliminated.name}’s pocket.</p>}</>}{preview.firstTimeAttendees.length>0&&<><h3>First Tribal attendance · +{preview.episode}</h3><p>{preview.firstTimeAttendees.map(castaway=>`${castaway.name} +${preview!.episode}`).join(' · ')}</p></>}{preview.preMerge&&<><h3>Pre-merge survival · +1</h3><p>{preview.survivingAttendees.map(castaway=>`${castaway.name} +1`).join(' · ')||'No remaining active castaways.'}{preview.eliminated&&preview.eliminationReason==='voted-out'&&!preview.eliminationScoringActive&&<><br/>{preview.eliminated.name} legacy penalty preserved</>}</p></>}</div>}
      {previewError&&<p className="scoring-error wide" role="alert">{previewError}</p>}
      <label className="wide">Note (optional)<input name="note" maxLength={500} placeholder="What happened at Tribal Council?"/></label>
      <button className="primary-button wide" disabled={loading||busy||!preview||resolved}>{busy?'Resolving…':resolved?'Resolved':'Resolve Tribal Council'}</button>
    </form>}
    {error&&<p className="scoring-error" role="alert">{error}</p>}{message&&<p className="success-banner" role="status">{message}</p>}
  </article>;
}
