'use client';
/* eslint-disable @next/next/no-img-element */
import Link from 'next/link';
import { useGame } from './game-provider';

const initials=(name:string)=>name.split(/\s+/).map((p)=>p[0]).join('').slice(0,2).toUpperCase();
export default function Home(){
 const {game,standings,castawayScores,loading}=useGame(); const hasScores=standings.some((p)=>p.score!==0); const leader=standings[0];
 if(loading) return <main className="loading-screen">Loading Season 51…</main>;
 return <main><header className="site-header"><Link className="brand" href="/"><span className="brand-mark">51</span><span><strong>Fantasy Survivor</strong><small>Outwit. Outdraft. Outscore.</small></span></Link><nav><a className="active" href="#standings">Standings</a><Link href="/draft">Draft board</Link><a href="#castaways">Castaways</a><Link href="/rules">Rules</Link><Link className="admin-link" href="/admin">Game master</Link></nav></header>
 <section className="hero"><div><p className="eyebrow"><span/> Survivor 51 · Episode {game.season.currentEpisode}</p><h1>The tribe has <em>spoken.</em></h1><p className="hero-copy">Every vote, challenge win, idol play, and perfectly timed blindside—scored in one place.</p></div><div className="torch-card"><span className="torch-kicker">{hasScores?'Current fantasy leader':'Season 51 setup'}</span><div className="champion-row"><span className="champion-avatar">{hasScores?initials(leader.name):'51'}</span><div><strong>{hasScores?leader.name:'Fresh slate'}</strong><small>{hasScores?`${leader.score.toFixed(1)} points`:'No scores entered yet'}</small></div></div><div className="champion-margin"><span>Castaways</span><strong>{game.castaways.length}</strong></div></div></section>
 <section className="content-grid" id="standings"><div className="panel leaderboard-panel"><div className="panel-heading"><div><p className="eyebrow dark">{hasScores?'Live leaderboard':'Player roster'}</p><h2>{hasScores?'Top of the tribe':'Everyone starts at zero'}</h2></div><span className="season-button">Survivor 51</span></div><div className="leader-list">{standings.map((p)=><div className={`leader-row ${hasScores&&p.rank===1?'winner':''}`} key={p.id}><span className="rank">{hasScores?p.rank:'—'}</span><span className="avatar">{initials(p.name)}</span><span className="leader-name"><strong>{p.name}</strong><small>{p.picks}</small></span><span className="change">{hasScores&&p.rank<=3?'TOP':'—'}</span><strong className="score">{p.score.toFixed(1)}</strong></div>)}</div><Link className="text-link" href="/draft">See every team and draft pick <span>→</span></Link></div><aside className="side-stack"><article className="rule-callout"><span className="rule-number">1.25×</span><div><strong>Blind-pick bonus</strong><p>Keep your round-three blind castaway and their points get a 25% boost.</p></div></article></aside></section>
 <section className="castaway-section" id="castaways"><div className="section-title"><div><p className="eyebrow dark">Season 51 cast</p><h2>Meet the castaways</h2></div><Link className="text-link inline" href="/rules">How scoring works <span>→</span></Link></div><div className="castaway-grid">{game.castaways.map((c)=><article className="castaway-card" key={c.id}><img src={c.imageUrl} alt={`${c.name}, Survivor 51 castaway`} loading="lazy"/><div className="castaway-body"><div className="castaway-status"><span className={`status-dot ${c.status==='active'?'active':''}`}/>{c.status==='active'?'Still alive':'Voted out'}</div><h3>{c.name}</h3><p className="castaway-meta">Age {c.age} · {c.occupation}</p><p className="castaway-bio">{c.bio}</p><div className="castaway-score"><span>{game.draftPicks.some((p)=>p.castawayId===c.id)?'Drafted':'Undrafted'}</span><strong>{castawayScores[c.id]??0} <small>pts</small></strong></div></div></article>)}</div></section>
 <footer><span>Fantasy Survivor</span><p>{standings.length} players · {game.castaways.length} castaways · one Sole Survivor</p></footer></main>;
}
